### ISSUE TITLE
Double negation when check cutomer data visibility in admin

### ISSUE THREAD

**Issue by nicoren-tangkoko** [magesuite/gdpr#3] opened 2020-06-02 08:36 UTC
Hi, 

I have found a bug due to double negation in back-office when i want to edit a customer with an admin account.

Current result : 
You don't have permision to view this page.

Expected result : 
The customer edit form is display correctly.

**Comment by diwipl** [comment] 2020-06-02 08:47
Hi,

This is not a bug. The idea of this module is that it's enabled by default so it will block access to any customer data until it's deactivated using ACL.

In order to allow access you need to create custom admin role and uncheck "Hide customer data".

**Comment by krisdante** [comment] 2020-06-02 11:41
Duplicate of https://github.com/magesuite/gdpr/issues/2

**Closed as completed by krisdante** 2020-06-02 11:41 UTC

**Comment by nicoren-tangkoko** [comment] 2020-06-02 11:45
OK thank you for the explain.
i close my PR.

**Comment by fritzmg** [comment] 2021-11-04 12:50
This seems a bit backwards in my opinion. If you have to create a custom admin role, just so you can uncheck "Hide customer data", you will now henceforth always have to add any additional permissions to that role when you install a new module etc. That's not really how administrator roles should work, should they? Administrators should have access to any new module by default (independently from this customer data setting).

**Comment by diwipl** [comment] 2021-11-04 13:17
Yes, that's a downside of our approach. We would need to rewrite the whole module to not use ACL and still to be enabled by default for everyone with the possibility to disable per role/user.

Currently, such implementation is not in our roadmap.

**Comment by krisdante** [comment] 2021-11-09 06:48
@fritzmg there was no other way to satisfy the GDPR requirement of privacy by default. The fact you are admin shall not give you the right to see personal data of shoppers. It has to be a conscious decision of your organization.

A good practice is anyway not to use the shop as Admin (same as you shall not use OS as root) but create an user with a limited subset of functionalities. And than such user can see personal data id your internal policy says so.

I know that GDPR is pita, but since it is there - let's respect it's rules and protect users privacy.

**Comment by fritzmg** [comment] 2021-11-09 08:27
> @fritzmg there was no other way to satisfy the GDPR requirement of privacy by default. The fact you are admin shall not give you the right to see personal data of shoppers. It has to be a conscious decision of your organization.

This extension does not prevent me from seeing the personal data, as I, as the administrator, can still see it in the database.

This can only be relevant for non-admin users, who only have access to the shop's back end and no access to the server otherwise.

**Comment by fritzmg** [comment] 2021-11-09 11:00
> A good practice is anyway not to use the shop as Admin (same as you shall not use OS as root) but create an user with a limited subset of functionalities. And than such user can see personal data id your internal policy says so.

But with your implementation any __non-__ Admin can view private data by default - as the option is unchecked by default.

> I know that GDPR is pita, but since it is there - let's respect it's rules and protect users privacy.

From my point of view GDPR is not a pita, but important and necessary. However there are many users, admins, whatever out there who wrongly believe that just installing certain extensions, e.g. a cookie consent tool, or this very extension, automatically makes them adhere to the rules that GDPR lays out - while in actuality their webshop likely still loads things like Google Tag Manager, YouTube videos etc. without consent, since their solution doesn't actually cover things that other extensions or customizations integrate.

Likewise, installing magesuite/gdpr doesn't automatically mean that you adhere to the rules that the GDPR lays out. The GDPR does not inherently say you need to hide private data to administrators of your site. Adhering to the rules of the GDPR means, among other things:

- Evaluating whether you need to collect private data at all or which private data you need to collect.
- Document which parties have access to said private data.
- Ensure that other parties cannot access said private data.

This extension tries to solve the latter, but in an unhelpful way and it gives unknown users a false sense of security.
